name = "frontend"
target = "javascript"
version = "1.0.0"

[dependencies]
shared = { path = "../shared" }
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.1.1 and < 6.0.0"
modem = ">= 2.1.0 and < 3.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
rsvp = ">= 1.1.0 and < 2.0.0"
# gleam_stdlib = ">= 0.60.0 and < 1.0.0"
# lustre = ">= 4.6.4 and < 5.0.0"
# plinth = ">= 0.5.7 and < 1.0.0"
# modem = ">= 2.0.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.4.0 and < 2.0.0"
lustre_dev_tools = ">= 1.8.2 and < 2.0.0"
