name = "frontend"
target = "javascript"
version = "1.0.0"

[dependencies]
shared = { path = "../shared" }
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "~> 4.1"
lustre_http = ">= 0.5.2 and < 1.0.0"
plinth = ">= 0.2.0 and < 1.0.0"
modem = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = "~> 1.2"
