name = "server"
version = "1.0.0"

[dependencies]
shared = { path = "../shared" }
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
mist = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.37.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
